### ISSUE TITLE
Example API notebook is outdated

### ISSUE THREAD

**Issue by hombit** [des-labs/desaccess-docs#1]
Sorry if it is a wrong place to highlight this issue, but it looks like API endpoint https://des.ncsa.illinois.edu/desaccess/api used by [`DESaccess_API_example.ipynb`](https://github.com/des-labs/desaccess-docs/blob/master/_static/DESaccess_API_example.ipynb) doesn't exist any more, it returns 404 and the following body:
```
Traceback (most recent call last):
  File "/home/worker/.local/lib/python3.8/site-packages/tornado/web.py", line 1680, in _execute
    result = self.prepare()
  File "/home/worker/.local/lib/python3.8/site-packages/tornado/web.py", line 2435, in prepare
    raise HTTPError(self._status_code)
tornado.web.HTTPError: HTTP 404: Not Found
```

**Comment by manning-ncsa** [comment]
Thanks for submitting an issue, and apologies for not seeing a notification that you did so. That 404 response is not actually an error; there is no API endpoint there. Take a look at a simplified example that I just created below, which only authenticates you and fetches an access token:

    https://gist.github.com/manning-ncsa/9ac2084eb8063b05e96735bdd3fdba2e#file-readme-md

Let me know if you have further questions.

**Comment by hombit** [comment]
I'm sorry, I missed the `login` part of the path in my script. Closing this

**Comment by hombit** [comment]
Hi Andrew!

I'm sorry for being silly, I missed the login part in the path in my script. I can login now!

Kostya

**Comment by hombit** [comment]
Actually I tried the notebook initially, but used email instead of username =) Maybe the notebook could have more specific error in the auth part, instead of try: ... except: sys.exit(1)?

**Comment by manning-ncsa** [comment]
That is a good point. I tried to make the web UI login screen convenient by allowing email addresses and usernames, but did not implement that flexibility for the underlying API. I cannot promise I will implement that anytime soon, but thanks for the suggestion.
